version: '3.6'

services:
  gate:
    build: 
      dockerfile: Dockerfile.cpu
      context: .
      args:
        BRANCH: main
    image: gate:dev
    volumes:
      - ./:/src:rw
      - /home/${USER}/gate:/home/gate
  